config/routes.rb
FisSki::Application.routes.draw do

  resources :penalties do
    collection do
      post :generate
    end
  end
  root :to => "standings#index"
  devise_for :users

  resources :races do
    resources :results
  end

  resources :competitors
  resources :standings

  resource :rule

end

app/views/shared/_age_class.html.haml
=highlighted_link(:age_class, age_class) {|v| decorate_age_class(v)}

app/views/shared/_age_group.html.haml
= highlighted_link :age_group, age_group

app/views/shared/_discipline.html.haml
= highlighted_link :discipline, discipline

app/views/shared/_index.html.haml
.row
  .col-md-1 Season:
  .col-md-11=render :partial => 'shared/season', :collection => (Season.fmc_earliest..Season.current.to_i).to_a
.row
  .col-md-1 Category:
  .col-md-11=render :partial => 'shared/age_group', collection: AgeClass::AGE_GROUPS
.row
  .col-md-1 Age Class:
  .col-md-11=render :partial => 'shared/age_class', :collection => ['All']+AgeClass.new(params.slice :age_group).classes
.row
  .col-md-1 Discipline:
  .col-md-11=render :partial => 'shared/discipline', :collection => ['All', 'Super G', 'Giant Slalom', 'Slalom']

app/views/shared/_menu.html.haml
=highlighted_link :controller, :standings
=highlighted_link :controller, :races
-#=link_to "Home", root_url
-#=link_to "Races", races_url
=link_to "Rules Simulation", edit_rule_url if params[:admin]

-#=link_to "Standings", root_url
-#-if user_signed_in?
-#  =link_to "Logout", destroy_user_session_url
-#  =link_to "Account Settings", edit_user_registration_url
-#-else
-#  =link_to "Login", new_user_session_url
-#  =link_to "Register", new_user_registration_url

app/views/shared/_season.html.haml
= highlighted_link :season, season