config/routes.rb
FisSki::Application.routes.draw do

  resources :penalties do
    collection do
      post :generate
    end
  end
  root :to => "standings#index"
  devise_for :users

  resources :races do
    resources :results
  end

  resources :competitors
  resources :standings

  resource :rule

end

app/models/penalty.rb
class Penalty < ActiveRecord::Base
end

app/controllers/penalties_controller.rb
class PenaltiesController < ApplicationController
  before_action :set_penalty, only: [:show, :edit, :update, :destroy]

  def generate
    Spawnling.new { Race.recalculate_penalty }
    redirect_to root_url
  end

  # GET /penalties
  # GET /penalties.json
  def index
    @penalties = Penalty.all
  end

  # GET /penalties/1
  # GET /penalties/1.json
  def show
  end

  # GET /penalties/new
  def new
    @penalty = Penalty.new
  end

  # GET /penalties/1/edit
  def edit
  end

  # POST /penalties
  # POST /penalties.json
  def create
    @penalty = Penalty.new(penalty_params)

    respond_to do |format|
      if @penalty.save
        format.html { redirect_to @penalty, notice: 'Penalty was successfully created.' }
        format.json { render :show, status: :created, location: @penalty }
      else
        format.html { render :new }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /penalties/1
  # PATCH/PUT /penalties/1.json
  def update
    respond_to do |format|
      if @penalty.update(penalty_params)
        format.html { redirect_to penalties_url }
        format.json { render :show, status: :ok, location: @penalty }
      else
        format.html { render :edit }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /penalties/1
  # DELETE /penalties/1.json
  def destroy
    @penalty.destroy
    respond_to do |format|
      format.html { redirect_to penalties_url, notice: 'Penalty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_penalty
    @penalty = Penalty.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def penalty_params
    params.require(:penalty).permit(:category, :min, :max)
  end
end

app/helpers/penalties_helper.rb
module PenaltiesHelper
end

app/views/penalties/_form.html.erb
<%= simple_form_for(@penalty) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :category %>
    <%= f.input :min %>
    <%= f.input :max %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/penalties/edit.html.erb
<h1>Editing Penalty</h1>

<%= render 'form' %>

<%= link_to 'Back', penalties_path %>

app/views/penalties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Penalties</h1>

<table>
    <thead>
    <tr>
        <th>Category</th>
        <th>Min</th>
        <th>Max</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @penalties.each do |penalty| %>
        <tr>
            <td><%= penalty.category %></td>
            <td><%= penalty.min %></td>
            <td><%= penalty.max %></td>
            <td><%= link_to 'Edit', edit_penalty_path(penalty) %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<p style="color: red">Attention! Click only once per genaration process which takes upto 10 minutes.</p>

<%= button_to 'Regenerate Penalties', generate_penalties_url, style: "color: red", data: {confirm: "Are you sure you want regenrate penalties? It may take up to 10 min. You should not attempt another regeneration during that time frame."} %>

app/views/penalties/new.html.erb
<h1>New Penalty</h1>

<%= render 'form' %>

<%= link_to 'Back', penalties_path %>

app/views/penalties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @penalty.category %>
</p>

<p>
  <strong>Min:</strong>
  <%= @penalty.min %>
</p>

<p>
  <strong>Max:</strong>
  <%= @penalty.max %>
</p>

<%= link_to 'Edit', edit_penalty_path(@penalty) %> |
<%= link_to 'Back', penalties_path %>