config/routes.rb
FisSki::Application.routes.draw do

  resources :penalties do
    collection do
      post :generate
    end
  end
  root :to => "standings#index"
  devise_for :users

  resources :races do
    resources :results
  end

  resources :competitors
  resources :standings

  resource :rule

end

app/models/rule.rb
class Rule
  include ActiveAttr::Model
  attribute :cup_points_rule, default: 15
  attribute :handicap, type: Float, default: 0.4
  attribute :min, type: Integer
  attribute :max, type: Integer
  attr_reader :cup_points_rule_instance

  delegate :cup_points, to: :cup_points_rule_instance

  def initialize(attr={})
    super(attr)
    @cup_points_rule_instance = Rules::CupPointsRule.new cup_points_rule
  end

  def max_races season, discipline
    max ||
        case discipline
          when 'Super G'
            4
          when 'Giant Slalom'
            7
          when 'Slalom'
            7
          else
            augment_season(season).max_races
        end
  end


  def min_races season, discipline
    min || (discipline && discipline != 'All' ? 0 : augment_season(season).min_races)
  end

  def augment_season season
    season.is_a?(Season) ? season : season ? Season.new(Season) : Season.current
  end
end

app/models/rules/cup_points_rule.rb
module Rules
  class CupPointsRule
    RULE15 = [25, 20, 15, 12]
    RULE30 = [100, 80, 60, 50, 45, 40, 36, 32, 29, 26, 24, 22, 20, 18, 16]
    attr_accessor :points

    def initialize(rule)
      self.points = rule.try(:to_i) == 30 ? RULE30 : RULE15
    end

    def cup_points rank
      rank ? points[rank - 1] || [points.last - (rank - points.length), 0].max : 0
    end
  end
end

app/models/rules/f_factor_rule.rb
module Rules
  class FFactorRule
    F_FACTORS = {
        2001 => {Downhill: 1280, :"Super G" => 1030, :"Giant Slalom" => 830, Slalom: 570},
        2003 => {Downhill: 1320, :"Super G" => 1050, :"Giant Slalom" => 870, Slalom: 600},
        2008 => {Downhill: 1350, :"Super G" => 1030, :"Giant Slalom" => 880, Slalom: 610},
        2009 => {Downhill: 1320, :"Super G" => 1060, :"Giant Slalom" => 880, Slalom: 600},
        2011 => {Downhill: 1330, :"Super G" => 1060, :"Giant Slalom" => 870, Slalom: 610},
        2013 => {Downhill: 1370, :"Super G" => 1050, :"Giant Slalom" => 890, Slalom: 620},
        2015 => {Downhill: 1250, :"Super G" => 1080, :"Giant Slalom" => 980, Slalom: 720},
    }

    def self.f_factor(race)
      F_FACTORS[F_FACTORS.keys.select { |s| s <= race.season }.max][race.discipline.to_sym]
    end
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  layout 'plain'

  def edit
    @rule = Rule.new(params.delete(:rule))
  end

  def create
    redirect_to :root
  end

  def destroy
    redirect_to :root
  end
end

app/views/rules/edit.html.haml
.row
  .col-md-12{role: :main}
    =simple_form_for @rule, url: rule_path do |f|
      =f.input :cup_points_rule, as: :radio_buttons, collection: [["top 15", 15], ["top 30", 30]], label: 'How many competitors should be awarded cup points?'
      =f.input :handicap, label: 'Handicap', hint: 'How many percent time per age year should be subtracted from time for overall results?'
      -#=f.input :min_races, label: 'Minimum Races', hint: 'Minimum number of races required to qualify for FMC'
      -#=f.input :max_races, label: 'Maximum Races', hint: 'Maximum number of races counted towards FMC'
      =f.button :submit, class: 'btn-primary'
      =link_to "Reset to Official Rules", rule_path, method: :delete, class: 'btn btn-danger'